name: Sample Check

on: [push, pull_request]

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a no-op command
      run: echo "This is a sample check"
